# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - wedding-web

on:
  push:
    branches:
      - release
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://mcr.microsoft.com/
        username: ${{ secrets.AzureAppService_ContainerUsername_cef6d0f66c48431aa2f218e101bd114c }}
        password: ${{ secrets.AzureAppService_ContainerPassword_93fb15e43fbd4fa68730c4d674c98433 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_cef6d0f66c48431aa2f218e101bd114c }}/appsvc/staticsite:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'wedding-web'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_a2c6c64f5a454a56be81e15b3da3cd00 }}
        images: 'mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_cef6d0f66c48431aa2f218e101bd114c }}/appsvc/staticsite:${{ github.sha }}'